import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { canAccessAgenda } from "@/lib/supabase/access";

export default async function ProgressPage() {
  let supabase; try { supabase = await createClient(); } catch { redirect("/login"); }
  const { data } = await supabase!.auth.getClaims(); const userId = data?.claims?.sub;
  if (!userId) redirect("/login"); if (!(await canAccessAgenda(userId))) redirect("/access-blocked");
  const { data: progress, error } = await supabase!.rpc("get_progress");
  if (error || !progress) return <main className="mx-auto min-h-screen max-w-xl px-5 py-8"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><p className="mt-12 text-slate-600">Não conseguimos carregar seu progresso agora.</p></main>;
  const foundation = progress.foundation as { completed?: number; total?: number; availability?: boolean; booking_path?: boolean; portfolio?: boolean } | null;
  return <main className="mx-auto min-h-screen w-full max-w-xl px-5 py-8 sm:px-8"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><p className="mt-10 text-sm font-semibold uppercase tracking-wide text-teal-700">Progresso</p><h1 className="mt-3 text-3xl font-bold leading-tight text-slate-900">Pequenos sinais do seu movimento</h1><section className="mt-8 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-teal-50 p-4"><p className="text-2xl font-bold text-teal-950">{progress.actions_completed ?? 0}</p><p className="mt-1 text-xs text-teal-900">ações feitas</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-bold text-slate-900">{progress.people_interested ?? 0}</p><p className="mt-1 text-xs text-slate-600">pessoas interessadas</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-bold text-slate-900">{progress.bookings ?? 0}</p><p className="mt-1 text-xs text-slate-600">agendamentos</p></div></section><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Seu momento</h2><p className="mt-2 leading-7 text-slate-600">{progress.moment_message}</p><p className="mt-5 text-sm font-semibold text-teal-800">{progress.next_focus}</p></section>{foundation && foundation.completed !== foundation.total && <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Básico para deixar a próxima ação possível</h2><p className="mt-2 text-sm text-slate-600">{foundation.completed} de {foundation.total} passos básicos concluídos</p><ul className="mt-4 grid gap-2 text-sm text-slate-700"><li>{foundation.availability ? "✓" : "○"} Tenho disponibilidade</li><li>{foundation.booking_path ? "✓" : "○"} Tenho como receber agendamentos</li><li>{foundation.portfolio ? "✓" : "○"} Tenho uma prova do meu serviço para mostrar</li></ul></section>}<Link href="/today" className="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-full bg-teal-800 px-5 font-semibold text-white">Voltar para Hoje</Link></main>;
}
