import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { canAccessAgenda } from "@/lib/supabase/access";

type AgendaSnapshot = { onboarding_required?: boolean; workspace?: { name: string; slug: string; timezone: string }; services?: Array<{ id: string; name: string; duration_minutes: number }>; appointments?: Array<{ id: string; service_name: string; customer_name: string; starts_at: string; ends_at: string; status: string }>; public_booking_url?: string };

export default async function AgendaPage() {
  let supabase; try { supabase = await createClient(); } catch { redirect("/login"); }
  const { data } = await supabase!.auth.getClaims(); const userId = data?.claims?.sub;
  if (!userId) redirect("/login"); if (!(await canAccessAgenda(userId))) redirect("/access-blocked");
  const { data: agenda, error } = await supabase!.rpc("get_agenda_snapshot");
  if (error || !agenda) return <main className="mx-auto min-h-screen max-w-xl px-5 py-10"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><p className="mt-12 text-slate-600">Não conseguimos carregar sua agenda agora.</p></main>;
  const snapshot = agenda as AgendaSnapshot;
  if (snapshot.onboarding_required) redirect("/onboarding");
  return <main className="mx-auto min-h-screen w-full max-w-2xl px-5 py-8 sm:px-8"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><header className="mt-10"><p className="text-sm font-semibold uppercase tracking-wide text-teal-700">Agenda</p><h1 className="mt-3 text-3xl font-bold leading-tight text-slate-900">Seu espaço de atendimento</h1><p className="mt-2 text-slate-600">Organize seus serviços e compartilhe um caminho simples para receber agendamentos.</p></header><section className="mt-8 rounded-2xl border border-teal-200 bg-teal-50 p-5"><h2 className="font-semibold text-teal-950">Link público de agendamento</h2><p className="mt-2 text-sm leading-6 text-teal-900">Compartilhe este caminho com quem quiser marcar com você.</p><p className="mt-4 break-all rounded-xl bg-white p-3 text-sm font-medium text-teal-950">{snapshot.public_booking_url}</p><Link href={snapshot.public_booking_url ?? "#"} className="mt-4 inline-flex min-h-11 items-center justify-center rounded-full bg-teal-800 px-5 font-semibold text-white">Abrir página pública</Link></section><section className="mt-8"><h2 className="text-xl font-bold text-slate-900">Serviços publicados</h2><div className="mt-4 grid gap-3">{snapshot.services?.map((service) => <div key={service.id} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{service.name}</p><p className="mt-1 text-sm text-slate-600">{service.duration_minutes} minutos · disponível para agendamento</p></div>)}</div></section><section className="mt-8"><h2 className="text-xl font-bold text-slate-900">Próximos agendamentos</h2>{snapshot.appointments?.length ? <div className="mt-4 grid gap-3">{snapshot.appointments.map((appointment) => <div key={appointment.id} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{appointment.service_name}</p><p className="mt-1 text-sm text-slate-600">{appointment.customer_name} · {new Date(appointment.starts_at).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-teal-700">{appointment.status}</p></div>)}</div> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-5 text-sm leading-6 text-slate-600">Ainda não há agendamentos. Compartilhe seu link para começar a receber horários.</p>}</section></main>;
}
