import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { canAccessAgenda } from "@/lib/supabase/access";
import { getBelevyAgendaSummary, type BelevyAgendaSummary } from "@/lib/belevy-integration";

type AgendaSnapshot = { onboarding_required?: boolean; workspace?: { name: string; slug: string; timezone: string }; services?: Array<{ id: string; name: string; duration_minutes: number }>; appointments?: Array<{ id: string; service_name: string; customer_name: string; starts_at: string; ends_at: string; status: string }>; public_booking_url?: string };

function formatAppointmentDate(value: string) {
  return new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
}

function renderBelevyConnection(summary: BelevyAgendaSummary) {
  if (summary.status === "connected") {
    return <section className="mt-8 rounded-2xl border border-teal-200 bg-teal-50 p-5"><p className="text-sm font-semibold uppercase tracking-wide text-teal-700">Belevy conectado</p><h2 className="mt-2 text-xl font-bold text-teal-950">Sua agenda oficial está no Belevy</h2><p className="mt-2 text-sm leading-6 text-teal-900">Use o Belevy para alterar horários, clientes, confirmações e disponibilidade. O Agenda 80/20 acompanha apenas sinais mínimos para orientar seu próximo movimento.</p><p className="mt-4 text-sm font-semibold text-teal-950">{summary.upcomingCount} horário(s) nos próximos 30 dias · {summary.completedLast30Days} atendimento(s) concluído(s) nos últimos 30 dias</p><a href={summary.publicUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center justify-center rounded-full bg-teal-800 px-5 font-semibold text-white">Abrir Belevy</a></section>;
  }
  if (summary.status === "expired") return <section className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Belevy opcional</p><h2 className="mt-2 text-xl font-bold text-amber-950">Sua conexão com o Belevy terminou</h2><p className="mt-2 text-sm leading-6 text-amber-900">O Agenda 80/20 continua funcionando. Você pode reativar o Belevy quando quiser para voltar a contar com a agenda operacional e as automações.</p><Link href="/belevy" className="mt-4 inline-flex min-h-11 items-center justify-center rounded-full border border-amber-800 px-5 font-semibold text-amber-900">Ver opções do Belevy</Link></section>;
  if (summary.status === "unavailable") return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold uppercase tracking-wide text-slate-500">Integração opcional</p><h2 className="mt-2 text-xl font-bold text-slate-900">O Belevy não respondeu agora</h2><p className="mt-2 text-sm leading-6 text-slate-600">Sua rotina do Agenda 80/20 continua disponível. Tente atualizar mais tarde para consultar os sinais da agenda operacional.</p></section>;
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold uppercase tracking-wide text-teal-700">Modo autônomo</p><h2 className="mt-2 text-xl font-bold text-slate-900">Você pode usar o Agenda 80/20 sem o Belevy</h2><p className="mt-2 text-sm leading-6 text-slate-600">O método, as ações, os registros e o progresso continuam disponíveis. O Belevy é opcional e acrescenta automação de agenda, clientes, lembretes e operação.</p><Link href="/belevy" className="mt-4 inline-flex text-sm font-semibold text-teal-800 underline underline-offset-4">Conhecer o Belevy opcional</Link></section>;
}

export default async function AgendaPage() {
  let supabase; try { supabase = await createClient(); } catch { redirect("/login"); }
  const { data } = await supabase!.auth.getClaims(); const userId = data?.claims?.sub; const userEmail = typeof data?.claims?.email === "string" ? data.claims.email : undefined;
  if (!userId) redirect("/login"); if (!(await canAccessAgenda(userId))) redirect("/access-blocked");
  const [{ data: agenda, error }, belevy] = await Promise.all([supabase!.rpc("get_agenda_snapshot"), getBelevyAgendaSummary(userEmail)]);
  if (error || !agenda) return <main className="mx-auto min-h-screen max-w-xl px-5 py-10"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><p className="mt-12 text-slate-600">Não conseguimos carregar sua agenda agora.</p></main>;
  const snapshot = agenda as AgendaSnapshot;
  if (snapshot.onboarding_required) redirect("/onboarding");
  const connected = belevy.status === "connected";
  const bookingUrl = connected ? belevy.publicUrl : snapshot.public_booking_url;
  const appointments = connected ? belevy.appointments.map((appointment) => ({ id: appointment.id, service_name: appointment.serviceName, customer_name: "", starts_at: appointment.startsAt, ends_at: appointment.endsAt, status: appointment.status })) : (snapshot.appointments ?? []);
  return <main className="mx-auto min-h-screen w-full max-w-2xl px-5 py-8 sm:px-8"><Link href="/today" className="text-sm font-semibold text-teal-700">← Hoje</Link><header className="mt-10"><p className="text-sm font-semibold uppercase tracking-wide text-teal-700">Agenda</p><h1 className="mt-3 text-3xl font-bold leading-tight text-slate-900">Seu espaço de atendimento</h1><p className="mt-2 text-slate-600">O Agenda 80/20 organiza seu próximo movimento. Quando conectado, o Belevy cuida da agenda oficial.</p></header>{renderBelevyConnection(belevy)}<section className="mt-8 rounded-2xl border border-teal-200 bg-teal-50 p-5"><h2 className="font-semibold text-teal-950">Link público de agendamento</h2><p className="mt-2 text-sm leading-6 text-teal-900">{connected ? "Este é o link oficial do Belevy." : "Este é o link básico disponível no modo autônomo."}</p><p className="mt-4 break-all rounded-xl bg-white p-3 text-sm font-medium text-teal-950">{bookingUrl}</p>{bookingUrl && (connected ? <a href={bookingUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center justify-center rounded-full bg-teal-800 px-5 font-semibold text-white">Abrir página pública</a> : <Link href={bookingUrl} className="mt-4 inline-flex min-h-11 items-center justify-center rounded-full bg-teal-800 px-5 font-semibold text-white">Abrir página pública</Link>)}</section><section className="mt-8"><h2 className="text-xl font-bold text-slate-900">Serviços publicados</h2><div className="mt-4 grid gap-3">{snapshot.services?.map((service) => <div key={service.id} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{service.name}</p><p className="mt-1 text-sm text-slate-600">{service.duration_minutes} minutos · disponível para agendamento</p></div>)}</div></section><section className="mt-8"><h2 className="text-xl font-bold text-slate-900">Próximos agendamentos</h2>{appointments.length ? <div className="mt-4 grid gap-3">{appointments.map((appointment) => <div key={appointment.id} className="rounded-xl border border-slate-200 bg-white p-4"><p className="font-semibold text-slate-900">{appointment.service_name}</p><p className="mt-1 text-sm text-slate-600">{appointment.customer_name ? `${appointment.customer_name} · ` : ""}{formatAppointmentDate(appointment.starts_at)}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-teal-700">{appointment.status}</p></div>)}</div> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-5 text-sm leading-6 text-slate-600">Ainda não há agendamentos. Compartilhe seu link para começar a receber horários.</p>}</section></main>;
}
